In [7]:
from bs4 import BeautifulSoup
#파일 읽기
with open('greenData/member_data.xml','r',encoding='utf-8-sig')as f:
    soup = BeautifulSoup(f,'xml')
#데이터추출(select 모두출력: 내가 지정한 member(반드시 태그여야함)안의 모든 것)
members = soup.select('member')

for m in members:
    name = m.select_one('name').text
    age = m.select_one('age').text
    city = m.select_one('city').text
    print(f"이름:{name}, 나이:{age}, city:{city}")

이름:김철수, 나이:25, city:서울
이름:이영희, 나이:30, city:부산
이름:박민수, 나이:22, city:대전

In [14]:
#import json => 아나콘다 라이브러리에 포함되어있어 import안해도 되지만, 간혹 안나오는 경우는 import해야나옴

#json.loads() :JSON형식의 문자열을 파이썬 사전(Dict)로 변환
#json.dumps() :파이썬 사전(Dict) 데이터를 JSON 문자열로 변환

# JSON -> 사전(Decoding)
json_str = '{"name":"Alice", "role":"admin", "level":5}'
data = json.loads(json_str)
print(data['name'], type(data))

# 사전-> JSON 문자열(Encoding)
user = {"id":7, "status":"online"}
userjson = json.dumps(user,indent=4) #indent는 들여쓰기 4칸 하겠다.
print(userjson)

Alice <class 'dict'>
{
    "id": 7,
    "status": "online"
}

In [24]:
#pandas 라이브러리란:  테이블형 데이터를 다룰수 있는 다양한 기능을 가진 라이브러리이다.
#raw data: 아직 데이터 분석을 위해 정제되지않은 기본데이터를 의미함
#pandas는 반드시 import해서 사용한다.
# 데이터를 다루는 방식 2가지
    #시리즈(series)는 1차원(행하나 또는 열하나)
    #데이터프레임(Dataframe)은 2차원(테이블형) 데이터이다.

import pandas as pd #라이브러리 임포트(대부분 pd로 사용)
#pd.판다스 함수 형태로 호출하여 사용한다.
#index는 행의 레이블(제목)을 의미한다.
#index를 지정하지 않으면 0부터 시작하는 인덱스 자동생성
#지정할 경우는 지정된 index로 사용
#seriesdata = pd.Series([70,80,90]) => 미지정의 경우 index는 0,1,2
seriesdata = pd.Series([70,80,90], index=['국어','영어','수학'])
seriesdata #print() 생략해도 똑같이 나옴
seriesdata.index #Index(['국어', '영어', '수학'], dtype='object') => object는 문자(string)라는뜻
seriesdata.index = ["미술","과학","사회"]
seriesdata #미술    70, 과학    80,사회    90

#Series 삭제 가능 : del seriesdata['미술']
del seriesdata['미술']
seriesdata #과학    80,사회    90

과학    80
사회    90
dtype: int64

In [32]:
# pandas 데이터 타입
# object : str 또는 혼용 데이터 타입(문자열)
# int64 : 파이썬의 int(정수)
# float64 : 파이썬의 float(부동소숫점)
# bool : 파이썬의 bool 또는 boolean(True 또는 False)
# datetime64 :날짜/시간
# timedelta : 두개의 datetime64간의 차이
seriesdata = pd.Series(['dave','alex','amir'])
seriesdata
seriesdata = pd.Series([1,2,3])
seriesdata

# int64의 정수를 float64 부동소숫점으로 변경가능
# 부동소수점 변경 명령어 : Series.astype(변경할 타입)
seriesdata.astype('float')
seriesdata
seriesdata = pd.Series(['dave',1,2,3])
seriesdata #0 :dave,1: 1,2: 2,3: 3, dtype: object
seriesdata = pd.Series([True,False,True])
seriesdata #0 :True,1: False,2: True, dtype: bool

0    1
1    2
2    3
dtype: int64

In [90]:
#데이터프레임(DataFrame): 2차원 테이블형태의 데이터이며, 데이터분석/머신러닝에서
                        #데이터 처리를 위해 주로사용함
#행(row)과 열(column)로 구성되어있다
#행의 레이블은 인덱스로, 열의 레이블은 컬럼으로 부른다.

df = pd.DataFrame({
    #"년도":[2000,2012,2013],
    "미국":[2.1,2.2,2.3],
    "한국":[0.4,0.5,0.45],
    "중국":[10,13,15]},
    index = [2000,2012,2013]
    )

#df
#df.columns #Index(['미국', '한국', '중국'], dtype='object')
#df.columns = {'일본','프랑스','독일'} #컬럼수정
#df.values

#df.set_index(값)
# df = df.set_index(['년도'])
# df.index.name='연도'
df

       미국    한국  중국
2000  2.1  0.40  10
2012  2.2  0.50  13
2013  2.3  0.45  15

In [100]:
# 데이터프레임 데이터 접근하기
# df.loc : index를 통해서 값을 찾음
# df.iloc : 인덱스 번호를 통해서 값을 찾음(0부터 시작)

df.loc[2000] #데이터 프레임의 레이블을 이용해 값을 출력
df.iloc[1] #이미 가지고 있는 1부터 시작하는 index값을 출력

#한국의 index가 2000인 데이터 값만 추출
print(df['한국'][2000])

#데이터프레임에 컬럼삭제:
#del df['미국']
df

#데이터프레임에 행(=가로) 삭제 : df.drop([인덱스이름])
df.drop([2012]) #=> 이건 2012 줄을 빼고 출력
df #=> 이건 그냥 다 출력

0.4

In [1]:
import pandas as pd

data = {
    '대여소':['강남','강남','홍대','홍대','잠실','잠실'],
    '이용자수':[120,150,80,90,200,100],
    '대여시간':[30,45,20,25,60,55],
    '이용일자':['2024-01-01','2024-01-02','2024-01-01','2024-01-02','2024-01-01','2024-01-02']
}
df = pd.DataFrame(data)

In [102]:
#Data자료를 이용해 이용자수가 100명 이상인 데이터만 출력하시오
#조건필터
#힌트: df[df['age'] > 20]

df[df['이용자수'] >= 100]

  대여소  이용자수  대여시간        이용일자
0  강남   120    30  2024-01-01
1  강남   150    45  2024-01-02
4  잠실   200    60  2024-01-01
5  잠실   100    55  2024-01-02

In [105]:
# 문제: 대여시간 기준으로 오름차순 정렬하여 출력하시오.
# 힌트: df.sort_values(by='price') =>디폴트값: 오름차순
df.sort_values(by='대여시간')
#내림차순 정렬: df.sort_values(by='price', ascending=False) => 값을 넣으면 내림차순
df.sort_values(by='대여시간', ascending=False)

  대여소  이용자수  대여시간        이용일자
4  잠실   200    60  2024-01-01
5  잠실   100    55  2024-01-02
1  강남   150    45  2024-01-02
0  강남   120    30  2024-01-01
3  홍대    90    25  2024-01-02
2  홍대    80    20  2024-01-01

In [106]:
#문제 : 총 이용량 컬럼을 이용자수 * 대여시간으로 계산하여 추가하시오.

df['총 이용량'] = df['이용자수'] * df['대여시간']
#실제 데이터에 추가한게 아니라, 출력만 시킨거임
df

  대여소  이용자수  대여시간        이용일자  총 이용량
0  강남   120    30  2024-01-01   3600
1  강남   150    45  2024-01-02   6750
2  홍대    80    20  2024-01-01   1600
3  홍대    90    25  2024-01-02   2250
4  잠실   200    60  2024-01-01  12000
5  잠실   100    55  2024-01-02   5500

In [117]:
# 문제 : Data자료를 이용해 대여소별 총 이용자수 구하여 출력하시오.
# 사용함수 : groupby()

result = df.groupby('대여소')['이용자수'].sum()

#=> 이 대여소별 이용자수를 내림차순하여 출력하시오.
result.sort_values(ascending=False)

대여소
잠실    300
강남    270
홍대    170
Name: 이용자수, dtype: int64

In [123]:
#문제: Data자료를 이용해 이용자수가 100 이상인 데이터만 추출하여 대여소별 평균 대여시간 구하여 출력하시오.
hundred = df[df['이용자수'] >= 100]
hundred.groupby('대여소')['대여시간'].mean()

대여소
강남    37.5
잠실    57.5
Name: 대여시간, dtype: float64

In [171]:
#문제: Data자료를 이용해 대여소별 "총이용량" 합계구하기
df['총 이용량'] = df['이용자수'] * df['대여시간']
print("대여소별 총 이용량 합계")
df.groupby('대여소')['총 이용량'].sum()

#문제: 가장 바쁜 날짜 찾기. => 이용일자별 이용자수 합계가 가장많은 날짜 출력
result02 = df.groupby('이용일자')['이용자수'].sum().sort_values(ascending=False)
print("가장 바쁜 날짜")
print(result02)
print(f"가장 바쁜 날짜: {result02.index[0]}")

#문제: 이용자 수 평균이 가장 높은 대여소찾기.
result03 = df.groupby('대여소')['이용자수'].mean().sort_values(ascending=False)
print("대여소별 평균 이용자수")
print(result03)
print(f"평균 이용자수 가장 높은 대여소: {result03.index[0]}")

대여소별 평균 이용자수
대여소
잠실    150.0
강남    135.0
홍대     85.0
Name: 이용자수, dtype: float64
평균 이용자수 가장 높은 대여소: 잠실